---

env:
  - distro: centos7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"

services: 
  - docker 

before_install:
  - 'docker pull geerlingguy/docker-${distro}-ansible:latest'

script:
  # Create a random file to store the container ID.
  - container_id=$(mktemp)
  # Run container detached, with our role mounted inside.
  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/ansible-role-ios_router:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest "${init}" > "${container_id}"'
  - >
    docker exec "$(cat ${container_id})" env TERM=xterm ansible --version
  # install dependencies
  - >
    docker exec "$(cat ${container_id})" ansible-galaxy install clay584.parse_genie
  # Check the role/playbook's syntax.
  - > 
    docker exec --tty "$(cat ${container_id})" 
    ansible-playbook /etc/ansible/roles/ansible-role-ios_router/tests/test.yml
    --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/